### ISSUE TITLE
FatFs.h no such file or directory

### ISSUE THREAD

**Issue by FT81xMania** [stm32duino/STM32SD#14]
I get this error when compile the CardInfo example on the NucleoF767ZI board:

`AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\libraries\STM32SD\src/SdFatFs.h:43:19: fatal error: FatFs.h: No such file or directory`

**Comment by fpistm** [comment]
Hi @FT81xMania ,
You have to install FatFs library as described in the Readme: https://github.com/stm32duino/STM32SD#dependency

Use the library manager or here: 
https://github.com/stm32duino/FatFs
