### ISSUE TITLE
Version 1.6.1 Issue

### ISSUE THREAD

**Issue by zpowellman** [stm32duino/STM32SD#16]
Trying to compile full.ino on black stm32F407VE board.
Get the following message:
#error "This library version required a STM32 core version > 1.6.1.\
I'm using Version 1.6.1 of the STM Core

Any ideas?
Thanks,
Dan

**Comment by zpowellman** [comment]
OOPs!  Just saw the > symbol.  I thought 1.6.1 was the latest.

**Comment by fpistm** [comment]
Right,install the latest release thanks the library manager not the zip of the master or try the core master.

**Comment by zpowellman** [comment]
Thanks for the response.

**Comment by zpowellman** [comment]
Frederic,

Thanks for the reply.  Was this library intended to be use with SPI or SDIO.  I’m using a STM32F407VET6 board?

Thanks again, the compile and download was successful but the app can’t find the card.

Dan

**Comment by fpistm** [comment]
SDIO or SDMMC.
For SPI use the SD library from arduino.

**Comment by zpowellman** [comment]
Thanks for the response.
