### ISSUE TITLE
STM32F103 series

### ISSUE THREAD

**Issue by zpowellman** [stm32duino/STM32SD#19]
It appears this library won't function for the STM32F103 Series.  Is that correct?  I'm using the Super Blue Pill board.
Thanks
Dan

**Comment by fpistm** [comment]
Hi, what do you mean by super BP?
I never tested for a F1 but this should work. If not then this would require a fix.

**Comment by zpowellman** [comment]
Hi. Thanks for responding. This is the super blue pill:
https://medium.com/swlh/super-blue-pill-like-stm32-blue-pill-but-better-6d341d9347da
Very versatile little board.  SD demo code won't compile for F1 Series.  I can send more info if you'd like?
Thanks again
Dan

**Comment by fpistm** [comment]
No, with info you provided that's enough.
On this board this is a SD card over SPI. Moreover the mcu does not have SDIO.
So, this is normal this doesn't build, simply  use the Arduino SD library.
This library is for MCU with card slot connected to SDIO or SDMMC.

**Comment by zpowellman** [comment]
Thanks a lot




Sent from my Galaxy Tab® S2


Get Outlook for Android







On Sat, Oct 26, 2019 at 9:31 AM -0600, "Frederic Pillon" <notifications@github.com> wrote:












No, with info you provided that's enough.

On this board this is a SD card over SPI. Moreover the mcu does not have SDIO.

So, this is normal this doesn't build, simply  use the Arduino SD library.

This library is for MCU with card slot connected to SDIO or SDMMC.
