### ISSUE TITLE
SPI2 on STM32F103C8T6 (Blue Pill)

### ISSUE THREAD

**Issue by GuillermoTell** [stm32duino/STM32SD#30]
Hi everyone,
I've been trying to read a microSD card using an adapter I bought but, I didn't notice the adapter already comes with a voltage shifter and a voltage regulator for 5v logic. As I didn't have a 5v Arduino available for testing, I decided to use a Blue Pill instead because some of the pins are 5v tolerant. Unfortunately, the SPI1 is not compatible and my only option is SPI2, but I have no idea about how to use it with the STM32SD library or the standard SD library.
Any ideas?
Thanks for your attention.

**Comment by fpistm** [comment]
This library do not use SPI, it uses SDIO or SDMMC peripherals. To use an SD with SPI use the default SD library from Arduino.Then to use other  SPI instance redefine each pins of the default SPI instance using: https://github.com/stm32duino/wiki/wiki/API#change-default-spi-instance-pins

Please use the forum for this kind of question/ support.
