### ISSUE TITLE
STM32F412VE compile error

### ISSUE THREAD

**Issue by jetbrainrobotics** [stm32duino/STM32SD#44]
The following STM32F412VE Arduino board is not available, hence I added the variant by copying the closest variant Generic_F412Rx and doing the necessary changes to files in it. On compiling the error I'm stuck at is :

/Library/Arduino15/packages/STM32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: libraries/SrcWrapper/stm32/PortNames.c.o: **in function `set_GPIO_Port_Clock':
PortNames.c:(.text.set_GPIO_Port_Clock+0xa2): undefined reference to `__HAL_RCC_GPIOF_CLK_ENABLE'**

/Library/Arduino15/packages/STM32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: PortNames.c:(.text.set_GPIO_Port_Clock+0xaa): **undefined reference to `__HAL_RCC_GPIOG_CLK_ENABLE'**

collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Generic STM32F4 series.

Any idea or hint will be helpful ?

**Comment by fpistm** [comment]
GitHu issue is not for requesting support only to report issue related to the repo. You can try on the forum.
