### ISSUE TITLE
Unstable work with sd card on stm32f4 

### ISSUE THREAD

**Issue by UncleSam27** [stm32duino/STM32SD#53]
I am using a STM32F4VE board  (Black F407VE in arduino)  to read and write an S29GL512N memory chip which contains 64 megabytes of data (which I need to store on a sd card). I write the data on the SD card using STM32SD library. I found that after writing 4-10 megabytes, a write error occurs on the card and the program cannot read or write anything to the card until the reboot. 

I tried changing boards and cards, but the problem persisted.

I assumed that the problem might be due to the microcontroller operating at too high a frequency.

I studied the library, increased the value of the SD_CLK_DIV variable in bsp_sd.c up to 8 and this change allowed me to work with the card without errors.

I did not find a way to specify this value manually when initializing the library, maybe it's worth providing such a way.

**Comment by fpistm** [comment]
Hi @UncleSam27 
thanks for the feedback, I will evaluate how to provide a way to define this.
