### ISSUE TITLE
fatal error: FatFs.h: No such file or directory 

### ISSUE THREAD

**Issue by daanvV** [stm32duino/STM32SD#64]
I'm using a nucleo 64, L452RE, using [example Datalogger.ino](https://github.com/stm32duino/STM32SD/blob/main/examples/Datalogger/Datalogger.ino)

Compilation returns: 
```
-> candidates: []
In file included from c:\Users\XXX\Documents\Arduino\libraries\STM32SD\src/STM32SD.h:23,
                 from R:\4. Projectgegevens\9999_10 IoT Asset mannagement\Werkdir\14_Test Software\nucleo_datalogger_SDIO\nucleo_datalogger_SDIO.ino:13:
c:\Users\XXXX\Documents\Arduino\libraries\STM32SD\src/SdFatFs.h:43:10: fatal error: FatFs.h: No such file or directory
   43 | #include "FatFs.h"
      |          ^~~~~~~~~
compilation terminated.

Using library STM32duino STM32SD at version 1.3.1 in folder: C:\Users\XXXX\Documents\Arduino\libraries\STM32SD 
exit status 1
```

Does anyone know what is going on here? I've looked for the "FatFs.h" file, can't find it anywhere.

**Comment by fpistm** [comment]
Hi  @daanvV 
You do not have installed the dependency library as stated in the library.properties and README.md:
https://github.com/stm32duino/STM32SD/blob/e20b7f367e5f999584a856a64845cbe0cbe143d7/library.properties#L10
https://github.com/stm32duino/STM32SD#dependency


When Arduino install it, it ask you if you want to install it:
![image](https://github.com/stm32duino/STM32SD/assets/20641798/cd25bb48-705a-47cb-9a54-f023a0a0c1d1)

**Comment by daanvV** [comment]
ah yes realised this just now too, thanks. Sorry about the silly question :/
