### ISSUE TITLE
DMA?

### ISSUE THREAD

**Issue by Split7fire** [stm32duino/STM32SD#65]
Hello! Thanks for your work! It's not a bug, but a question: any chance to work with uSD with DMA?

P.S. I'll describe my problem - may be someone has a better option for me.) I have a project (FREERTOS + STM32SD) where first task constantly sample an ADC with period of 250 us. Also I have another task, where sdcard routines work. I buffer data to a 16384 B array and try to write to uSD in background. (I mean sdCard task is lower priority than other tasks.) 16384 B array writes to uSD in about 8.5 ms. If I raise priority for uSD task, everything seems normal, but ADC task get no time. Any help appreciated.

**Comment by fpistm** [comment]
Please open a discussion for questionor on the forum.

**Comment by Split7fire** [comment]
ok, thanks
