### ISSUE TITLE
Don't know how to define pins

### ISSUE THREAD

**Issue by Semsem-220109** [stm32duino/STM32SD#69]
Hi everyone, 
I wanted to ask, if i want to define pins to go with my specific type of board, do I use 
`PinMap_SD_CK[] 
PinMap_SD_DATA0[] 
PinMap_SD_DATA1[] 
PinMap_SD_DATA2[] 
PinMap_SD_DATA3[] 
PinMap_SD_DATA4[] 
PinMap_SD_DATA5[] 
PinMap_SD_DATA6[] 
PinMap_SD_DATA7[] 
`

Or 
`Sd2Card card; 
  card.setDx(PE12, PE13, PE14, PE15); 
  card.setCMD(PB_14); // using PinName 
  card.setCK(PB15); 
  card.init(); ` 

Or 
`card.init(PE12, PE13, PE14, PE15, PB14, PB15); 
  SD.begin(SD_DETECT_PIN, PE12, PE13, PE14, PE15, PB14, PB15); `

Can you please give me an example code of how to declare pins only, in other words the void Setup(); and everything above it please !
Thank's in advance

**Comment by fpistm** [comment]
https://github.com/stm32duino/STM32SD#sdiosdmmc-pins-definition

**Comment by Semsem-220109** [comment]
I read this but I found other things below, It will be nice explaining @fpistm
