### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by Semsem-220109** [stm32duino/STM32SD#70]
I get this error while compiling the Card Info sketch like it is (just declaring the card.init(); without parameters) :

`In file included from C:\Users\Lenovo\Documents\Arduino\libraries\STM32duino_STM32SD\src/Sd2Card.h:40:0,
                 from C:\Users\Lenovo\Documents\Arduino\libraries\STM32duino_STM32SD\src/STM32SD.h:22,
                 from C:\Users\Lenovo\AppData\Local\Temp\.arduinoIDE-unsaved2023918-80668-1jvezxa.0ec2\CardInfo\CardInfo.ino:12:
C:\Users\Lenovo\Documents\Arduino\libraries\STM32duino_STM32SD\src/bsp_sd.h:47:10: fatal error: PinNames.h: No such file or directory
 #include "PinNames.h"
          ^~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1`

Can someone help ? I couldn't find that library anywhere

**Comment by fpistm** [comment]
Which STM32 core you used ?
This library is for https://github.com/stm32duino/Arduino_Core_STM32
And PinNames.h is not a library just part of the core:
--> https://github.com/stm32duino/Arduino_Core_STM32/blob/main/cores/arduino/stm32/PinNames.h
